apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: yinglu91/t-auth
      context: auth
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - infra/k8s/auth-depl.yaml
      - infra/k8s/ingress-srv.yaml
